const clubsData = [
    { "naam": "Avanti/Post Makelaardij", "stad": "Alphen aan den Rijn"},
    { "naam": "Albatros", "stad": "Zwijndrecht"},
    { "naam": "Arena", "stad": "Rhenen"},
    { "naam": "Blauw Wit (K)", "stad": "Goes"},
    { "naam": "Blauw Zwart", "stad": "Wierden"},
    { "naam": "Blauw-Wit (A)", "stad": "Amsterdam"},
    { "naam": "Conventus", "stad": "Zwijndrecht"},
    { "naam": "Dalto/Klaverblad Verzekeringen", "stad": "Driebergen-Rijsenburg"},
    { "naam": "De Corvers", "stad": "Hilversum"},
    { "naam": "De Meervogels", "stad": "Zoetermeer"},
    { "naam": "DES (D)", "stad": "Delft"},
    { "naam": "DES (V)", "stad": "Vierlingsbeek"},
    { "naam": "Die Haghe/Rosario Kozijnen", "stad": "'S-Gravenhage"},
    { "naam": "DOS (W)", "stad": "Westbroek"},
    { "naam": "Dunas", "stad": "'S-Gravenhage"},
    { "naam": "DVO/Transus", "stad": "Bennekom"},
    { "naam": "Erasmus", "stad": "Rotterdam"},
    { "naam": "Excelsior", "stad": "Delft"},
    { "naam": "Fiducia", "stad": "Vleuten"},
    { "naam": "Fiks", "stad": "Oestgeest"},
    { "naam": "Fluks", "stad": "Noordwijk"},
    { "naam": "Focus", "stad": "Etten-leur"},
    { "naam": "Fortuna/Ruitenheer", "stad": "Delft"},
    { "naam": "Gemini", "stad": "Gouda"},
    { "naam": "GKV (G)", "stad": "Gorinchem"},
    { "naam": "GKV (H)", "stad": "'S-Gravenhage"},
    { "naam": "Hebbes", "stad": "Utrecht"},
    { "naam": "HKC (He)", "stad": "Hengelo"},
    { "naam": "HKC (U)", "stad": "Utrecht"},
    { "naam": "Huizen", "stad": "Huizen"},
    { "naam": "Ijsselvogels", "stad": "Moordrecht"},
    { "naam": "KCC/CK Kozijnen", "stad": "Capelle aan den Ijssel"},
    { "naam": "KCR", "stad": "Ridderkerk"},
    { "naam": "Kinderdijk", "stad": "Alblasserdam"},
    { "naam": "KOAG", "stad": "Krimpen aan den Ijssel"},
    { "naam": "Korbis", "stad": "Waddinxveen"},
    { "naam": "Koveni", "stad": "Nieuwegein"},
    { "naam": "KVS/Remondis", "stad": "'S-Gravenhage"},
    { "naam": "KZ/Danaïden", "stad": "Leiden"},
    { "naam": "KZ/Keukensale.com", "stad": "Koog aan de Zaan"},
    { "naam": "LDODK/Rinsma Modeplein", "stad": "Gorredijk"},
    { "naam": "Luno", "stad": "Linschoten"},
    { "naam": "LYNX", "stad": "'S-Gravenhage"},
    { "naam": "Maassluis", "stad": "Maassluis"},
    { "naam": "Madjoe", "stad": "Rijnsburg"},
    { "naam": "Merwede/Multiplaat", "stad": "Sliedrecht"},
    { "naam": "Nexus", "stad": "Schiedam"},
    { "naam": "Nieuwerkerk", "stad": "Nieuwerkerk aan den IJssel"},
    { "naam": "Nikantes", "stad": "Hoogvliet"},
    { "naam": "NIO", "stad": "Rotterdam"},
    { "naam": "ONDO (G)", "stad": "'S-Gravenhage"},
    { "naam": "ONDO (M)", "stad": "Middelburg"},
    { "naam": "Oosterkwartier", "stad": "Haarlem"},
    { "naam": "OVVO", "stad": "Maarssen"},
    { "naam": "OZC", "stad": "Rotterdam"},
    { "naam": "RDZ", "stad": "Zeist"},
    { "naam": "Reeuwijk", "stad": "Reeuwijk"},
    { "naam": "SKV", "stad": "Sleeuwijk"},
    { "naam": "t' Capproen", "stad": "Hellevoetsluis"},
    { "naam": "Trekvogels", "stad": "Rotterdam"},
    { "naam": "Valto/Verbakel Bouwbedrijf", "stad": "De Lier"},
    { "naam": "Vitesse (Ba)", "stad": "Barendrecht"},
    { "naam": "Vriendenschaar", "stad": "Bodegraven"},
    { "naam": "ZKV", "stad": "Zuidland"},
    { "naam": "Zuid '27", "stad": "Rotterdam"}
];