const clubsData = [
    { "naam": "Avanti/Post Makelaardij", "stad": "Alphen aan den Rijn"},
    { "naam": "De Corvers", "stad": "Hilversum"},
    { "naam": "DOS (W)", "stad": "Westbroek"},
    { "naam": "Dunas", "stad": "'S-Gravenhage"},
    { "naam": "Erasmus", "stad": "Rotterdam"},
    { "naam": "Excelsior", "stad": "Delft"},
    { "naam": "Gemini", "stad": "Gouda"},
    { "naam": "Huizen", "stad": "Huizen"},
    { "naam": "Ijsselvogels", "stad": "Moordrecht"},
    { "naam": "KCC/CK Kozijnen", "stad": "Capelle aan den Ijssel"},
    { "naam": "KCR", "stad": "Ridderkerk"},
    { "naam": "KOAG", "stad": "Krimpen aan den Ijssel"},
    { "naam": "Korbis", "stad": "Waddinxveen"},
    { "naam": "KZ/Danaïden", "stad": "Leiden"},
    { "naam": "KZ/Keukensale.com", "stad": "Koog aan de Zaan"},
    { "naam": "Maassluis", "stad": "Maassluis"},
    { "naam": "Nieuwerkerk", "stad": "Nieuwerkerk aan den IJssel"},
    { "naam": "Nikantes", "stad": "Hoogvliet"},
    { "naam": "Oosterkwartier", "stad": "Haarlem"},
    { "naam": "RDZ", "stad": "Zeist"},
    { "naam": "Reeuwijk", "stad": "Reeuwijk"},
    { "naam": "SKV", "stad": "Sleeuwijk"},
    { "naam": "t' Capproen", "stad": "Hellevoetsluis"},
    { "naam": "Trekvogels", "stad": "Rotterdam"},
    { "naam": "Valto/Verbakel Bouwbedrijf", "stad": "De Lier"},
    { "naam": "Vitesse (Ba)", "stad": "Barendrecht"},
    { "naam": "Vriendenschaar", "stad": "Bodegraven"},
    { "naam": "ZKV", "stad": "Zuidland"},
    { "naam": "Zuid '27", "stad": "Rotterdam"}
];